## torch.autograd
https://pytorch.org/docs/stable/autograd.html

In [1]:
import torch
import numpy as np
print(torch.__version__)

0.4.1.post2


In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [4]:
print(y.grad_fn)

In [5]:
z = y * y * 3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>)
tensor(27., grad_fn=<MeanBackward1>)


In [6]:
a = torch.randn(2, 2)    # requires_grad default to False
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)   # requires_grad_() changes requires_grad flag in-place.
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)         # with requires_grad set to True, autograd starts to track all operations on a tensor

False
True


## Automatic differentiation
call `backward()` on a tensor to compute the derivatives. If Tensor is a scalar (i.e. it holds a one element data), you don’t need to specify any arguments to `backward()`, however if it has more elements, you need to specify a `gradient` argument that is a tensor of matching shape.

*Note:* `backward()` accumulates gradients in the leaves and you might need to zero them before calling it.

In [7]:
out.backward() # equivalent to out.backward(torch.tensor(1))
print(x.grad)  # d(out)/dx|x=1 ==> 3/2(x+2)|x=1  ==> 9/2 = 4.5   

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [8]:
x = torch.ones(3, requires_grad=True)
y = x * 2
gradients = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float)
y.backward(gradients) 
print(x.grad)         # dy/dx = 2, dy/dx|x=0.1 = 2*0.1 = 0.2

tensor([0.2000, 2.0000, 0.0020])


In [9]:
# stop autograd from tracking history on tensors
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
