## torch.Tensor
https://pytorch.org/docs/stable/tensors.html

`torch.Tensor` is an alias for the default tensor type `torch.FloatTensor`

In [22]:
import torch
import numpy as np
print(torch.__version__)

0.4.1.post2


In [26]:
x = torch.tensor([1, 2, 3]) # create tesnor directly from python list
print(x)
y = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]])) # from numpy array
print(y)

tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


**NOTE:** `torch.tensor()` always copies `data`. If you have a Tensor data and just want to change its `requires_grad` flag, use `requires_grad_()` or `detach()` to avoid a copy. If you have a numpy array and want to avoid a copy, use `torch.as_tensor()`.

In [29]:
m = np.array([1, 1, 1])
n = torch.as_tensor(m)  # m and n share data
print(n)
m[0] = 2
print(n)

tensor([1, 1, 1])
tensor([2, 1, 1])


In [2]:
x = torch.empty(5, 3) # specify size and create an uninitialized tensor
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [3]:
x = torch.rand(5, 3) # randomly initialized tensor
print(x)

tensor([[0.0104, 0.3117, 0.8229],
        [0.1097, 0.2213, 0.2282],
        [0.9426, 0.2544, 0.0842],
        [0.4172, 0.2231, 0.0649],
        [0.9170, 0.0727, 0.1110]])


In [4]:
x = torch.randn(5, 3)
print(x)

tensor([[-1.3224, -0.3148,  0.8519],
        [ 0.6643,  0.0403, -0.3317],
        [-1.3914,  0.2191,  1.3154],
        [-0.5725,  0.1418,  0.3219],
        [-0.3627, -0.6597, -1.6727]])


In [5]:
x = torch.zeros(2, 5, dtype=torch.long) # init tensor with zeros
print(x)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])


In [25]:
x = x.new_ones(5, 3, dtype=torch.double) # create tensor from an existing tensor, inherit properties if not specified
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4546,  0.2603, -0.1721],
        [ 0.3261, -1.1363, -1.1793],
        [-0.7265,  0.4723, -0.9502],
        [ 0.8988,  0.2237,  0.0657],
        [-2.0047, -0.5466,  0.4404]])


In [19]:
torch.abs(x) # return result with a new tensor
print(x)     # the original tensor is not changed

tensor([[ 0.6474,  2.1717,  2.0280],
        [ 0.1501,  0.2278,  0.8367],
        [ 0.6700, -0.4034, -0.5096],
        [ 0.0723,  0.6437, -0.1734],
        [-0.8439, -0.0299, -0.0788]])


In [20]:
torch.FloatTensor.abs_(x) # computes the result in-place and return the modified tensor
print(x)

tensor([[0.6474, 2.1717, 2.0280],
        [0.1501, 0.2278, 0.8367],
        [0.6700, 0.4034, 0.5096],
        [0.0723, 0.6437, 0.1734],
        [0.8439, 0.0299, 0.0788]])


Use `torch.Tensor.item()` to get a Python number from a tensor containing a single value

In [32]:
x = torch.tensor([[1]])
print(x)
print(x.item())

tensor([[1]])
1


### [Tensor attributes](https://pytorch.org/docs/stable/tensor_attributes.html#tensor-attributes-doc)
 - `torch.dtype`
 - `torch.device`
 - `torch.layout`
 - to change an existing tensor's `torch.device` and/or `torch.dtype`, use `to()` method on the tensor

## Oeprations

In [38]:
x = torch.tensor([1, 1, 1])
y = torch.tensor([2, 2, 2])
print(x + y)
print(torch.add(x, y)) # add x, y and returns a new tensor
result = torch.empty(1, 3, dtype=torch.long)
torch.add(x, y, out=result) # provide an output tensor as argument
print(result)

tensor([3, 3, 3])
tensor([3, 3, 3])
tensor([3, 3, 3])


In [39]:
y.add_(x) # add x to y (in-place)
print(y)

tensor([3, 3, 3])


In [40]:
# indexing and slicing like numpy
x = torch.randn(4, 4)
print(x)
print(x[0, :])

tensor([[ 0.3449, -0.8789, -1.5781, -0.7846],
        [ 0.5610, -0.1188,  1.3234, -0.1684],
        [-0.1062,  0.5519, -0.5740, -0.9802],
        [ 0.6671,  0.7173,  0.2714,  0.9912]])
tensor([ 0.3449, -0.8789, -1.5781, -0.7846])


In [41]:
# resize/reshape tensor
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Numpy bridge
torch tensor and numpy array can be easily converted. They will share memory locations and changing one will change the other.

In [44]:
# from torch to numpy
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [43]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [45]:
# from numpy to torch
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA tensors
Tensors can be moved onto any device using the `to()` method

In [47]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[ 1.3449,  0.1211, -0.5781,  0.2154],
        [ 1.5610,  0.8812,  2.3234,  0.8316],
        [ 0.8938,  1.5519,  0.4260,  0.0198],
        [ 1.6671,  1.7173,  1.2714,  1.9912]], device='cuda:0')
tensor([[ 1.3449,  0.1211, -0.5781,  0.2154],
        [ 1.5610,  0.8812,  2.3234,  0.8316],
        [ 0.8938,  1.5519,  0.4260,  0.0198],
        [ 1.6671,  1.7173,  1.2714,  1.9912]], dtype=torch.float64)
